In [1]:
import os
import pandas as pd
import numpy as np
import pyodbc

os.chdir(r'D:\Projects\Export Dashboard')

In [2]:
NewExport = pd.read_excel('NewExport.xlsx' , sheet_name=  'CurrencyParityRate')

2.	Total Sales = SUMX(FactSale,FactSale[RealAmount]*FactSale[CurrencyParityRateDolar])

In [3]:
cnxn = pyodbc.connect(r'Driver=SQL Server;Server=172.31.50.99;Database=QlikView;Trusted_Connection=yes;')

In [4]:
import pyodbc

cnxn = pyodbc.connect(
    r'DRIVER=SQL Server;'
    r'SERVER=172.31.50.98;'
    r'DATABASE=QlikView;'
    r'UID=ai;'
    r'PWD=&1A%iyBQ#8J1;'
)
cursor = cnxn.cursor()





FactSaleExportCurrency = pd.read_sql_query('''SELECT MainDate , RealAmount , CurrencyDesc , applicationcode FROM [QlikView].[aggr].[Vw_FactSaleExportCurrency]''', cnxn)



cursor.close()   # close the cursor
cnxn.close()

C:\Users\Soleimani.Yeganeh\AppData\Local\Temp\ipykernel_18288\1445740252.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  FactSaleExportCurrency = pd.read_sql_query('''SELECT MainDate , RealAmount , CurrencyDesc , applicationcode FROM [QlikView].[aggr].[Vw_FactSaleExportCurrency]''', cnxn)

In [5]:
FactSaleExportCurrency

         MainDate   RealAmount CurrencyDesc  applicationcode
0        14030601    45000.000        دینار               22
1        14020301    10000.000        دینار               22
2        14010101    10000.000        دینار               22
3        14030301    19559.228        دینار               22
4        14010201    39000.000        دینار               22
...           ...          ...          ...              ...
3753023  14000601  1880525.000         ريال                1
3753024  14000701        0.000         ريال                1
3753025  14000301  3489920.000         ريال                1
3753026  13990701        0.000         ريال                1
3753027  13991001  3854160.000         ريال                1

[3753028 rows x 4 columns]

In [6]:
dict = {'دینار' : '107',
        'افغاني' : '103',
         'دلار امريكا' : '101',
          'ريال' : '108',
           'يورو' : '102',
            'روبل' : '106' }

In [7]:
FactSaleExportCurrency['CurrencyCode'] = FactSaleExportCurrency['CurrencyDesc'].map(dict)
FactSaleExportCurrency['CurrencyCode'].unique()

array(['107', '103', '101', '108', nan, '102', '106'], dtype=object)

In [8]:
FactSaleExportCurrency['YearMonth'] = FactSaleExportCurrency['MainDate'].str[:6]

In [9]:
NewExport

,CurrencyName,CurrencyID,YearMonth,CurrencyParityRateDolar,CurrencyParityRateDerham,DollartoDirham
0,US Dollar,101,139501,1.000000e+00,NaN,3.672820
1,Afghani,103,139501,1.466810e-02,NaN,NaN
2,Turkish Lira,104,139501,3.508000e-01,NaN,NaN
3,Rial,108,139501,2.876938e-05,NaN,NaN
4,US Dollar,101,139502,1.000000e+00,NaN,3.672746
...,...,...,...,...,...,...
865,Canadian Dollar,105,140402,7.350200e-01,NaN,NaN
866,Rouble,106,140402,1.171000e-02,NaN,NaN
867,Iraq Dinar,107,140402,7.650000e-04,NaN,NaN
868,Rial,108,140402,9.717170e-07,NaN,NaN
869,Derham,109,140402,2.722940e-01,NaN,NaN

In [10]:
NewExport['YearMonth'] = NewExport['YearMonth'].astype(str)

In [11]:
NewExport

,CurrencyName,CurrencyID,YearMonth,CurrencyParityRateDolar,CurrencyParityRateDerham,DollartoDirham
0,US Dollar,101,139501,1.000000e+00,NaN,3.672820
1,Afghani,103,139501,1.466810e-02,NaN,NaN
2,Turkish Lira,104,139501,3.508000e-01,NaN,NaN
3,Rial,108,139501,2.876938e-05,NaN,NaN
4,US Dollar,101,139502,1.000000e+00,NaN,3.672746
...,...,...,...,...,...,...
865,Canadian Dollar,105,140402,7.350200e-01,NaN,NaN
866,Rouble,106,140402,1.171000e-02,NaN,NaN
867,Iraq Dinar,107,140402,7.650000e-04,NaN,NaN
868,Rial,108,140402,9.717170e-07,NaN,NaN
869,Derham,109,140402,2.722940e-01,NaN,NaN

In [12]:
FactSaleExportCurrency

,MainDate,RealAmount,CurrencyDesc,applicationcode,CurrencyCode,YearMonth
0,14030601,45000.000,دینار,22,107,140306
1,14020301,10000.000,دینار,22,107,140203
2,14010101,10000.000,دینار,22,107,140101
3,14030301,19559.228,دینار,22,107,140303
4,14010201,39000.000,دینار,22,107,140102
...,...,...,...,...,...,...
3753023,14000601,1880525.000,ريال,1,108,140006
3753024,14000701,0.000,ريال,1,108,140007
3753025,14000301,3489920.000,ريال,1,108,140003
3753026,13990701,0.000,ريال,1,108,139907
3753027,13991001,3854160.000,ريال,1,108,139910

In [13]:
FactSaleExportCurrency['YearMonth'] = FactSaleExportCurrency['YearMonth'].astype("string")
NewExport['YearMonth'] = NewExport['YearMonth'].astype("string")

In [14]:
NewExport['CurrencyID'] = NewExport['CurrencyID'].astype("string")
FactSaleExportCurrency['CurrencyCode'] = FactSaleExportCurrency['CurrencyCode'].astype("string")

In [15]:
merged_data = pd.merge(FactSaleExportCurrency ,NewExport , right_on= ['YearMonth' ,'CurrencyID' ] , left_on= ['YearMonth' ,'CurrencyCode'])

In [16]:
merged_data.columns

Index(['MainDate', 'RealAmount', 'CurrencyDesc', 'applicationcode',
       'CurrencyCode', 'YearMonth', 'CurrencyName', 'CurrencyID',
       'CurrencyParityRateDolar', 'CurrencyParityRateDerham',
       'DollartoDirham'],
      dtype='object')

In [17]:
merged_data2 = merged_data[['RealAmount' , 'MainDate' , 'CurrencyDesc' , 'YearMonth' , 'CurrencyName' , 'CurrencyParityRateDolar']]

In [18]:
merged_data2['RealAmount-RateDolar'] = merged_data2['RealAmount'] * merged_data2['CurrencyParityRateDolar']

C:\Users\Soleimani.Yeganeh\AppData\Local\Temp\ipykernel_18288\252106682.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data2['RealAmount-RateDolar'] = merged_data2['RealAmount'] * merged_data2['CurrencyParityRateDolar']

In [19]:
merged_data2['RealAmount-RateDolar'].sum()

602627077.0456597

In [20]:
merged_data2

,RealAmount,MainDate,CurrencyDesc,YearMonth,CurrencyName,CurrencyParityRateDolar,RealAmount-RateDolar
0,45000.000,14030601,دینار,140306,Iraq Dinar,0.000765,34.425000
1,10000.000,14020301,دینار,140203,Iraq Dinar,0.000765,7.650000
2,10000.000,14010101,دینار,140101,Iraq Dinar,0.000685,6.850000
3,19559.228,14030301,دینار,140303,Iraq Dinar,0.000765,14.962809
4,39000.000,14010201,دینار,140102,Iraq Dinar,0.000685,26.715000
...,...,...,...,...,...,...,...
3731718,1880525.000,14000601,ريال,140006,Rial,0.000004,6.844435
3731719,0.000,14000701,ريال,140007,Rial,0.000004,0.000000
3731720,3489920.000,14000301,ريال,140003,Rial,0.000004,14.905234
3731721,0.000,13990701,ريال,139907,Rial,0.000003,0.000000
3731722,3854160.000,13991001,ريال,139910,Rial,0.000004,15.415869

In [22]:
merged_data2['RealAmount-RateDolar'][merged_data2['MainDate'] > '14040101'].sum()

9186470.01683987

In [23]:
merged_data2

,RealAmount,MainDate,CurrencyDesc,YearMonth,CurrencyName,CurrencyParityRateDolar,RealAmount-RateDolar
0,45000.000,14030601,دینار,140306,Iraq Dinar,0.000765,34.425000
1,10000.000,14020301,دینار,140203,Iraq Dinar,0.000765,7.650000
2,10000.000,14010101,دینار,140101,Iraq Dinar,0.000685,6.850000
3,19559.228,14030301,دینار,140303,Iraq Dinar,0.000765,14.962809
4,39000.000,14010201,دینار,140102,Iraq Dinar,0.000685,26.715000
...,...,...,...,...,...,...,...
3731718,1880525.000,14000601,ريال,140006,Rial,0.000004,6.844435
3731719,0.000,14000701,ريال,140007,Rial,0.000004,0.000000
3731720,3489920.000,14000301,ريال,140003,Rial,0.000004,14.905234
3731721,0.000,13990701,ريال,139907,Rial,0.000003,0.000000
3731722,3854160.000,13991001,ريال,139910,Rial,0.000004,15.415869